version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html 
      - ./styles:/usr/share/nginx/styles              
      - ./images:/usr/share/nginx/images              
      - ./icons:/usr/share/nginx/icons                     
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
